### PR TITLE
fix: false positive when accessing shadow dom in constructor

### LINKED ISSUE #46: no-constructor-attributes error when manipulating the Shadow DOM
Using `this.shadowRoot.append()` in a WC constructor leads to a _[wc/no-constructor-attributes](https://github.com/43081j/eslint-plugin-wc/blob/master/docs/rules/no-constructor-attributes.md)_ error.

```js
class Demo extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: "open" });

    // ERROR: Attributes must not be interacted with in the constructor as the element may not be ready yet.
    // eslintwc/no-constructor-attributes
    this.shadowRoot.append(
      p(button("previous", "<"), button("next", ">"))
    );
  }
}
```

Yet, the [standard](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance) only restricts manipulations of the **light** DOM, and manipulating the Shadow DOM doesn't lead to any runtime error.

IMO, this is a false positive.

### PR DESCRIPTION
**Pull request by noelmace**
Fix #46

## Explainer

A custom element instance can be created programmatically with `document.createElement`. Which means the class constructor may be called **before** the element has access to the DOM. This is why we can't modify the element itself in the constructor, including its light dom.

Yet, a shadow DOM is created _"inside"_ the element and doesn't need to wait until this element is attached to another DOM to be available. Therefore, no error will occur when accessing the shadowRoot inside a custom element constructor.

Actually, this is even the recommended approach, as it will allow building the Web Component "content" ahead of time (which may lead to better performance), in a 100% controlled environment (which may avoid some bugs).

## Quote from the [HTML Standard](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance)

- The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.
- In general, work should be deferred to connectedCallback as much as possible—especially work involving fetching resources or rendering. ***However, note that connectedCallback can be called more than once, so any initialization work that is truly one-time will need a guard to prevent it from running twice.***
- In general, ***the constructor should be used to set up initial state*** and default values, and to set up event listeners ***and possibly a shadow root***.

### CODE REVIEW

**Comment by noelmace** [comment]
@43081j Do you think I should add this explainer to [/docs/rules/no-constructor-attributes.md](https://github.com/43081j/eslint-plugin-wc/blob/master/docs/rules/no-constructor-attributes.md) ?

File: src/test/rules/no-constructor-attributes_test.ts [hunk 1]
```diff
@@ -55,6 +55,58 @@ ruleTester.run('no-constructor-attributes', rule, {
       code: `class NonElement {
       constructor() { this.getAttribute('x'); this.appendChild(c); }
     }`
+    },
+    {
+      code: `class Foo extends HTMLElement {
+        constructor() {
+          this.shadowRoot.hasAttribute('foo');
```
Comment (43081j) [inline src/test/rules/no-constructor-attributes_test.ts:62]: these methods won't actually exist on a shadow root afaik. the test should probably be that a shadowroot child can be mutated:

```ts
this.shadowRoot.children[0].getAttribute('foo');
```

or something along those lines. 

the rule will still check such an impossible case, but thats ok i think to keep it simple

Comment (43081j) [reply src/test/rules/no-constructor-attributes_test.ts:62]: funnily enough just saw they were already here! previous-me made a mistake, good if we can fix that in this branch 😂

**Comment by 43081j** [comment]
i think it would be best to update the docs but maybe an explainer isn't necessary here. we can just change the docs to specify explicitly that it applies to the light DOM i think.

something like this:

> Constructors of custom elements should never interact with their own light DOM or attributes as the element may not yet be upgraded.
> 
> Do note that interaction with the element's shadow DOM is perfectly valid at this point as it does not interfere with
> the DOM tree of the consumer.

File: src/test/rules/no-constructor-attributes_test.ts (hunk 1 above)
Comment (noelmace) [reply src/test/rules/no-constructor-attributes_test.ts:62]: Yeah, I just copy-pasted the old tests :smile: I'll fix that during the weekend.

File: docs/rules/no-constructor-attributes.md [hunk 2]
```diff
@@ -1,39 +1,63 @@
 # Disallows interaction with attributes in constructors (no-constructor-attributes)
 
-Constructors of custom elements should never interact with the DOM or
-attributes as the element may not yet be upgraded.
+Constructors of custom elements should never interact with their own light DOM and attributes as the element will not be connected to the DOM when created programmatically (i.e. using `document.createElement()`).
```
Comment (43081j) [inline docs/rules/no-constructor-attributes.md:3]: nit: can we maintain the line length here? (max 80)

Comment (43081j) [reply docs/rules/no-constructor-attributes.md:3]: also really its not because it won't be connected to the DOM, rather that it may not yet be upgraded. it could be in DOM but not yet upgraded and would break assumptions the consumer might have around createElement semantics.

i'd keep the old wording (upgraded vs connected)

**Review by 43081j — APPROVED** [review]

**Comment by 43081j** [comment]
thanks for the effort here @noelmace , looks good to me so will try get a release out in the next day or so 👍
